// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package aed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AEDServiceClient is the client API for AEDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AEDServiceClient interface {
	// Store a single AED
	Upsert(ctx context.Context, in *AED, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Store multiple AED
	BatchUpsert(ctx context.Context, in *AEDs, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get a list of AED by from/to, symbol, period and network
	Get(ctx context.Context, in *AEDFilter, opts ...grpc.CallOption) (*AEDs, error)
	// Get aeds for all the given periods
	GetAEDsForPeriods(ctx context.Context, in *PeriodsFilter, opts ...grpc.CallOption) (*AEDs, error)
}

type aEDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAEDServiceClient(cc grpc.ClientConnInterface) AEDServiceClient {
	return &aEDServiceClient{cc}
}

func (c *aEDServiceClient) Upsert(ctx context.Context, in *AED, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aed.AEDService/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aEDServiceClient) BatchUpsert(ctx context.Context, in *AEDs, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aed.AEDService/BatchUpsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aEDServiceClient) Get(ctx context.Context, in *AEDFilter, opts ...grpc.CallOption) (*AEDs, error) {
	out := new(AEDs)
	err := c.cc.Invoke(ctx, "/aed.AEDService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aEDServiceClient) GetAEDsForPeriods(ctx context.Context, in *PeriodsFilter, opts ...grpc.CallOption) (*AEDs, error) {
	out := new(AEDs)
	err := c.cc.Invoke(ctx, "/aed.AEDService/GetAEDsForPeriods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AEDServiceServer is the server API for AEDService service.
// All implementations should embed UnimplementedAEDServiceServer
// for forward compatibility
type AEDServiceServer interface {
	// Store a single AED
	Upsert(context.Context, *AED) (*emptypb.Empty, error)
	// Store multiple AED
	BatchUpsert(context.Context, *AEDs) (*emptypb.Empty, error)
	// Get a list of AED by from/to, symbol, period and network
	Get(context.Context, *AEDFilter) (*AEDs, error)
	// Get aeds for all the given periods
	GetAEDsForPeriods(context.Context, *PeriodsFilter) (*AEDs, error)
}

// UnimplementedAEDServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAEDServiceServer struct {
}

func (UnimplementedAEDServiceServer) Upsert(context.Context, *AED) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedAEDServiceServer) BatchUpsert(context.Context, *AEDs) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpsert not implemented")
}
func (UnimplementedAEDServiceServer) Get(context.Context, *AEDFilter) (*AEDs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAEDServiceServer) GetAEDsForPeriods(context.Context, *PeriodsFilter) (*AEDs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAEDsForPeriods not implemented")
}

// UnsafeAEDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AEDServiceServer will
// result in compilation errors.
type UnsafeAEDServiceServer interface {
	mustEmbedUnimplementedAEDServiceServer()
}

func RegisterAEDServiceServer(s grpc.ServiceRegistrar, srv AEDServiceServer) {
	s.RegisterService(&AEDService_ServiceDesc, srv)
}

func _AEDService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AED)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AEDServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aed.AEDService/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AEDServiceServer).Upsert(ctx, req.(*AED))
	}
	return interceptor(ctx, in, info, handler)
}

func _AEDService_BatchUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AEDs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AEDServiceServer).BatchUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aed.AEDService/BatchUpsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AEDServiceServer).BatchUpsert(ctx, req.(*AEDs))
	}
	return interceptor(ctx, in, info, handler)
}

func _AEDService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AEDFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AEDServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aed.AEDService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AEDServiceServer).Get(ctx, req.(*AEDFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _AEDService_GetAEDsForPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeriodsFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AEDServiceServer).GetAEDsForPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aed.AEDService/GetAEDsForPeriods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AEDServiceServer).GetAEDsForPeriods(ctx, req.(*PeriodsFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// AEDService_ServiceDesc is the grpc.ServiceDesc for AEDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AEDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aed.AEDService",
	HandlerType: (*AEDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _AEDService_Upsert_Handler,
		},
		{
			MethodName: "BatchUpsert",
			Handler:    _AEDService_BatchUpsert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AEDService_Get_Handler,
		},
		{
			MethodName: "GetAEDsForPeriods",
			Handler:    _AEDService_GetAEDsForPeriods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aed-grpc.proto",
}
