// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: aed-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";
import { AED, AEDs, Period } from "./aed";
import { Empty } from "./google/protobuf/empty";
import { Timestamp } from "./google/protobuf/timestamp";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "aed";

export interface AEDFilter {
  Symbol: string;
  From:
    | Date
    | undefined;
  /** Apply from as equal to retrieve only this one bucket for the given time */
  SingleBucket?: boolean | undefined;
  To: Date | undefined;
  Network: Network;
  Period:
    | Period
    | undefined;
  /** Indicate if the data should be backfilled with the previous period if no data is found */
  Backfill: boolean;
  /** Indicates if the data is allowed to be retrieved from the cache (default: false - no cache) */
  AllowCache: boolean;
  OrganizationID: string;
}

export interface PeriodsFilter {
  Symbol: string;
  Periods: PeriodBucket[];
}

export interface PeriodBucket {
  Period: Period | undefined;
  Timestamp: Date | undefined;
}

function createBaseAEDFilter(): AEDFilter {
  return {
    Symbol: "",
    From: undefined,
    SingleBucket: undefined,
    To: undefined,
    Network: 0,
    Period: undefined,
    Backfill: false,
    AllowCache: false,
    OrganizationID: "",
  };
}

export const AEDFilter = {
  encode(message: AEDFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Symbol !== "") {
      writer.uint32(10).string(message.Symbol);
    }
    if (message.From !== undefined) {
      Timestamp.encode(toTimestamp(message.From), writer.uint32(18).fork()).ldelim();
    }
    if (message.SingleBucket !== undefined) {
      writer.uint32(24).bool(message.SingleBucket);
    }
    if (message.To !== undefined) {
      Timestamp.encode(toTimestamp(message.To), writer.uint32(34).fork()).ldelim();
    }
    if (message.Network !== 0) {
      writer.uint32(40).int32(message.Network);
    }
    if (message.Period !== undefined) {
      Period.encode(message.Period, writer.uint32(50).fork()).ldelim();
    }
    if (message.Backfill !== false) {
      writer.uint32(56).bool(message.Backfill);
    }
    if (message.AllowCache !== false) {
      writer.uint32(64).bool(message.AllowCache);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(74).string(message.OrganizationID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AEDFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAEDFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Symbol = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.From = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.SingleBucket = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.To = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.Period = Period.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.Backfill = reader.bool();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.AllowCache = reader.bool();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AEDFilter {
    return {
      Symbol: isSet(object.Symbol) ? globalThis.String(object.Symbol) : "",
      From: isSet(object.From) ? fromJsonTimestamp(object.From) : undefined,
      SingleBucket: isSet(object.SingleBucket) ? globalThis.Boolean(object.SingleBucket) : undefined,
      To: isSet(object.To) ? fromJsonTimestamp(object.To) : undefined,
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      Period: isSet(object.Period) ? Period.fromJSON(object.Period) : undefined,
      Backfill: isSet(object.Backfill) ? globalThis.Boolean(object.Backfill) : false,
      AllowCache: isSet(object.AllowCache) ? globalThis.Boolean(object.AllowCache) : false,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
    };
  },

  toJSON(message: AEDFilter): unknown {
    const obj: any = {};
    if (message.Symbol !== "") {
      obj.Symbol = message.Symbol;
    }
    if (message.From !== undefined) {
      obj.From = message.From.toISOString();
    }
    if (message.SingleBucket !== undefined) {
      obj.SingleBucket = message.SingleBucket;
    }
    if (message.To !== undefined) {
      obj.To = message.To.toISOString();
    }
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Period !== undefined) {
      obj.Period = Period.toJSON(message.Period);
    }
    if (message.Backfill !== false) {
      obj.Backfill = message.Backfill;
    }
    if (message.AllowCache !== false) {
      obj.AllowCache = message.AllowCache;
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AEDFilter>, I>>(base?: I): AEDFilter {
    return AEDFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AEDFilter>, I>>(object: I): AEDFilter {
    const message = createBaseAEDFilter();
    message.Symbol = object.Symbol ?? "";
    message.From = object.From ?? undefined;
    message.SingleBucket = object.SingleBucket ?? undefined;
    message.To = object.To ?? undefined;
    message.Network = object.Network ?? 0;
    message.Period = (object.Period !== undefined && object.Period !== null)
      ? Period.fromPartial(object.Period)
      : undefined;
    message.Backfill = object.Backfill ?? false;
    message.AllowCache = object.AllowCache ?? false;
    message.OrganizationID = object.OrganizationID ?? "";
    return message;
  },
};

function createBasePeriodsFilter(): PeriodsFilter {
  return { Symbol: "", Periods: [] };
}

export const PeriodsFilter = {
  encode(message: PeriodsFilter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Symbol !== "") {
      writer.uint32(10).string(message.Symbol);
    }
    for (const v of message.Periods) {
      PeriodBucket.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PeriodsFilter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeriodsFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Symbol = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Periods.push(PeriodBucket.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PeriodsFilter {
    return {
      Symbol: isSet(object.Symbol) ? globalThis.String(object.Symbol) : "",
      Periods: globalThis.Array.isArray(object?.Periods)
        ? object.Periods.map((e: any) => PeriodBucket.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PeriodsFilter): unknown {
    const obj: any = {};
    if (message.Symbol !== "") {
      obj.Symbol = message.Symbol;
    }
    if (message.Periods?.length) {
      obj.Periods = message.Periods.map((e) => PeriodBucket.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeriodsFilter>, I>>(base?: I): PeriodsFilter {
    return PeriodsFilter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeriodsFilter>, I>>(object: I): PeriodsFilter {
    const message = createBasePeriodsFilter();
    message.Symbol = object.Symbol ?? "";
    message.Periods = object.Periods?.map((e) => PeriodBucket.fromPartial(e)) || [];
    return message;
  },
};

function createBasePeriodBucket(): PeriodBucket {
  return { Period: undefined, Timestamp: undefined };
}

export const PeriodBucket = {
  encode(message: PeriodBucket, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Period !== undefined) {
      Period.encode(message.Period, writer.uint32(10).fork()).ldelim();
    }
    if (message.Timestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.Timestamp), writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PeriodBucket {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeriodBucket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Period = Period.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Timestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PeriodBucket {
    return {
      Period: isSet(object.Period) ? Period.fromJSON(object.Period) : undefined,
      Timestamp: isSet(object.Timestamp) ? fromJsonTimestamp(object.Timestamp) : undefined,
    };
  },

  toJSON(message: PeriodBucket): unknown {
    const obj: any = {};
    if (message.Period !== undefined) {
      obj.Period = Period.toJSON(message.Period);
    }
    if (message.Timestamp !== undefined) {
      obj.Timestamp = message.Timestamp.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeriodBucket>, I>>(base?: I): PeriodBucket {
    return PeriodBucket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeriodBucket>, I>>(object: I): PeriodBucket {
    const message = createBasePeriodBucket();
    message.Period = (object.Period !== undefined && object.Period !== null)
      ? Period.fromPartial(object.Period)
      : undefined;
    message.Timestamp = object.Timestamp ?? undefined;
    return message;
  },
};

export type AEDServiceService = typeof AEDServiceService;
export const AEDServiceService = {
  /** Store a single AED */
  upsert: {
    path: "/aed.AEDService/Upsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AED) => Buffer.from(AED.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AED.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Store multiple AED */
  batchUpsert: {
    path: "/aed.AEDService/BatchUpsert",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AEDs) => Buffer.from(AEDs.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AEDs.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  /** Get a list of AED by from/to, symbol, period and network */
  get: {
    path: "/aed.AEDService/Get",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AEDFilter) => Buffer.from(AEDFilter.encode(value).finish()),
    requestDeserialize: (value: Buffer) => AEDFilter.decode(value),
    responseSerialize: (value: AEDs) => Buffer.from(AEDs.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AEDs.decode(value),
  },
  /** Get aeds for all the given periods */
  getAeDsForPeriods: {
    path: "/aed.AEDService/GetAEDsForPeriods",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: PeriodsFilter) => Buffer.from(PeriodsFilter.encode(value).finish()),
    requestDeserialize: (value: Buffer) => PeriodsFilter.decode(value),
    responseSerialize: (value: AEDs) => Buffer.from(AEDs.encode(value).finish()),
    responseDeserialize: (value: Buffer) => AEDs.decode(value),
  },
} as const;

export interface AEDServiceServer extends UntypedServiceImplementation {
  /** Store a single AED */
  upsert: handleUnaryCall<AED, Empty>;
  /** Store multiple AED */
  batchUpsert: handleUnaryCall<AEDs, Empty>;
  /** Get a list of AED by from/to, symbol, period and network */
  get: handleUnaryCall<AEDFilter, AEDs>;
  /** Get aeds for all the given periods */
  getAeDsForPeriods: handleUnaryCall<PeriodsFilter, AEDs>;
}

export interface AEDServiceClient extends Client {
  /** Store a single AED */
  upsert(request: AED, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  upsert(
    request: AED,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  upsert(
    request: AED,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Store multiple AED */
  batchUpsert(request: AEDs, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  batchUpsert(
    request: AEDs,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  batchUpsert(
    request: AEDs,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** Get a list of AED by from/to, symbol, period and network */
  get(request: AEDFilter, callback: (error: ServiceError | null, response: AEDs) => void): ClientUnaryCall;
  get(
    request: AEDFilter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AEDs) => void,
  ): ClientUnaryCall;
  get(
    request: AEDFilter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AEDs) => void,
  ): ClientUnaryCall;
  /** Get aeds for all the given periods */
  getAeDsForPeriods(
    request: PeriodsFilter,
    callback: (error: ServiceError | null, response: AEDs) => void,
  ): ClientUnaryCall;
  getAeDsForPeriods(
    request: PeriodsFilter,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AEDs) => void,
  ): ClientUnaryCall;
  getAeDsForPeriods(
    request: PeriodsFilter,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AEDs) => void,
  ): ClientUnaryCall;
}

export const AEDServiceClient = makeGenericClientConstructor(AEDServiceService, "aed.AEDService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AEDServiceClient;
  service: typeof AEDServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
