// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: aed.proto

package aed

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Source int32

const (
	Source_SOURCE_NOT_USED Source = 0
	Source_SOURCE_EXCHANGE Source = 1 // Source: exchange trades
	Source_SOURCE_ATS      Source = 2 // Alternative Trading System
	Source_SOURCE_DEX      Source = 3 // Decentralized Exchange + AMM (anywhere on the blockchain)
	Source_SOURCE_INTERNAL Source = 4 // eg. admin dashboard
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_NOT_USED",
		1: "SOURCE_EXCHANGE",
		2: "SOURCE_ATS",
		3: "SOURCE_DEX",
		4: "SOURCE_INTERNAL",
	}
	Source_value = map[string]int32{
		"SOURCE_NOT_USED": 0,
		"SOURCE_EXCHANGE": 1,
		"SOURCE_ATS":      2,
		"SOURCE_DEX":      3,
		"SOURCE_INTERNAL": 4,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[0].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[0]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{0}
}

type Series int32

const (
	Series_SERIES_NOT_USED    Series = 0
	Series_INTERNAL_TRADES    Series = 1 // Source: dex trades, Usage: general trade graphs, supports TradeView-like graphing tools (ohlc)
	Series_MARKET_DATA_STOCKS Series = 2 // Source: external market data provider for the general stock market (can be more than 1 provider, but only a single provider per stock)
	Series_USER_PERFORMANCE   Series = 3 // Source: user account data, Usage: tracks user's portfolio/trading performance over various time periods
	Series_BILLING            Series = 4 // Source: billing data, Usage: tracks billing data for the organization
	Series_REFERRAL           Series = 5 // Source: referral data, Usage: tracks referral data for the organization
)

// Enum value maps for Series.
var (
	Series_name = map[int32]string{
		0: "SERIES_NOT_USED",
		1: "INTERNAL_TRADES",
		2: "MARKET_DATA_STOCKS",
		3: "USER_PERFORMANCE",
		4: "BILLING",
		5: "REFERRAL",
	}
	Series_value = map[string]int32{
		"SERIES_NOT_USED":    0,
		"INTERNAL_TRADES":    1,
		"MARKET_DATA_STOCKS": 2,
		"USER_PERFORMANCE":   3,
		"BILLING":            4,
		"REFERRAL":           5,
	}
)

func (x Series) Enum() *Series {
	p := new(Series)
	*p = x
	return p
}

func (x Series) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Series) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[1].Descriptor()
}

func (Series) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[1]
}

func (x Series) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Series.Descriptor instead.
func (Series) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{1}
}

type Field int32

const (
	Field_FIELD_NOT_USED   Field = 0
	Field_OPEN             Field = 1
	Field_HIGH             Field = 2
	Field_LOW              Field = 3
	Field_CLOSE            Field = 4
	Field_VOLUME           Field = 5
	Field_NUMBER_OF_TRADES Field = 6
	Field_INVERTED_VOLUME  Field = 7
	Field_MARKET_CAP       Field = 8
	Field_EPS              Field = 9
	Field_PE_RATIO         Field = 10
	Field_YIELD            Field = 11
	Field_OPEN_TIME        Field = 12
	Field_CLOSE_TIME       Field = 13
	Field_FIRST_PRICE      Field = 14 // First price in the time window
	Field_LAST_PRICE       Field = 15 // Last price in the time window
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0:  "FIELD_NOT_USED",
		1:  "OPEN",
		2:  "HIGH",
		3:  "LOW",
		4:  "CLOSE",
		5:  "VOLUME",
		6:  "NUMBER_OF_TRADES",
		7:  "INVERTED_VOLUME",
		8:  "MARKET_CAP",
		9:  "EPS",
		10: "PE_RATIO",
		11: "YIELD",
		12: "OPEN_TIME",
		13: "CLOSE_TIME",
		14: "FIRST_PRICE",
		15: "LAST_PRICE",
	}
	Field_value = map[string]int32{
		"FIELD_NOT_USED":   0,
		"OPEN":             1,
		"HIGH":             2,
		"LOW":              3,
		"CLOSE":            4,
		"VOLUME":           5,
		"NUMBER_OF_TRADES": 6,
		"INVERTED_VOLUME":  7,
		"MARKET_CAP":       8,
		"EPS":              9,
		"PE_RATIO":         10,
		"YIELD":            11,
		"OPEN_TIME":        12,
		"CLOSE_TIME":       13,
		"FIRST_PRICE":      14,
		"LAST_PRICE":       15,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[2].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[2]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field.Descriptor instead.
func (Field) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{2}
}

type PeriodType int32

const (
	PeriodType_PERIOD_TYPE_DO_NOT_USE PeriodType = 0
	PeriodType_PERIOD_TYPE_MINUTE     PeriodType = 1
	PeriodType_PERIOD_TYPE_HOUR       PeriodType = 2
	PeriodType_PERIOD_TYPE_DAY        PeriodType = 3
	PeriodType_PERIOD_TYPE_WEEK       PeriodType = 4
	PeriodType_PERIOD_TYPE_MONTH      PeriodType = 5
	PeriodType_PERIOD_TYPE_YEAR       PeriodType = 6
)

// Enum value maps for PeriodType.
var (
	PeriodType_name = map[int32]string{
		0: "PERIOD_TYPE_DO_NOT_USE",
		1: "PERIOD_TYPE_MINUTE",
		2: "PERIOD_TYPE_HOUR",
		3: "PERIOD_TYPE_DAY",
		4: "PERIOD_TYPE_WEEK",
		5: "PERIOD_TYPE_MONTH",
		6: "PERIOD_TYPE_YEAR",
	}
	PeriodType_value = map[string]int32{
		"PERIOD_TYPE_DO_NOT_USE": 0,
		"PERIOD_TYPE_MINUTE":     1,
		"PERIOD_TYPE_HOUR":       2,
		"PERIOD_TYPE_DAY":        3,
		"PERIOD_TYPE_WEEK":       4,
		"PERIOD_TYPE_MONTH":      5,
		"PERIOD_TYPE_YEAR":       6,
	}
)

func (x PeriodType) Enum() *PeriodType {
	p := new(PeriodType)
	*p = x
	return p
}

func (x PeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[3].Descriptor()
}

func (PeriodType) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[3]
}

func (x PeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeriodType.Descriptor instead.
func (PeriodType) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{3}
}

type AEDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AEDs          []*AED                 `protobuf:"bytes,1,rep,name=AEDs,proto3" json:"AEDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AEDs) Reset() {
	*x = AEDs{}
	mi := &file_aed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AEDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AEDs) ProtoMessage() {}

func (x *AEDs) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AEDs.ProtoReflect.Descriptor instead.
func (*AEDs) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{0}
}

func (x *AEDs) GetAEDs() []*AED {
	if x != nil {
		return x.AEDs
	}
	return nil
}

type AED struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationID string                 `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"` // Denom1:Denom2
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Period         *Period                `protobuf:"bytes,4,opt,name=Period,proto3" json:"Period,omitempty"`
	MetaData       *metadata.MetaData     `protobuf:"bytes,5,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	UserID         *string                `protobuf:"bytes,6,opt,name=UserID,proto3,oneof" json:"UserID,omitempty"` // Time series stored at user level for profit/loss, etc
	Value          []*Value               `protobuf:"bytes,100,rep,name=Value,proto3" json:"Value,omitempty"`
	Series         Series                 `protobuf:"varint,101,opt,name=Series,proto3,enum=aed.Series" json:"Series,omitempty"`
	Source         *Source                `protobuf:"varint,102,opt,name=Source,proto3,enum=aed.Source,oneof" json:"Source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AED) Reset() {
	*x = AED{}
	mi := &file_aed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AED) ProtoMessage() {}

func (x *AED) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AED.ProtoReflect.Descriptor instead.
func (*AED) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{1}
}

func (x *AED) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *AED) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AED) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AED) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

func (x *AED) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *AED) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *AED) GetValue() []*Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AED) GetSeries() Series {
	if x != nil {
		return x.Series
	}
	return Series_SERIES_NOT_USED
}

func (x *AED) GetSource() Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return Source_SOURCE_NOT_USED
}

type Value struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Field     Field                  `protobuf:"varint,1,opt,name=Field,proto3,enum=aed.Field" json:"Field,omitempty"`
	StringVal *string                `protobuf:"bytes,2,opt,name=StringVal,proto3,oneof" json:"StringVal,omitempty"` // String value
	Int64Val  *int64                 `protobuf:"varint,3,opt,name=Int64Val,proto3,oneof" json:"Int64Val,omitempty"`  // Integer value
	// Reject NaN / Inf. Price-like positivity is enforced by the message CEL above.
	Float64Val    *float64 `protobuf:"fixed64,4,opt,name=Float64Val,proto3,oneof" json:"Float64Val,omitempty"` // Float value
	BoolVal       *bool    `protobuf:"varint,5,opt,name=BoolVal,proto3,oneof" json:"BoolVal,omitempty"`        // Boolean value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_aed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetField() Field {
	if x != nil {
		return x.Field
	}
	return Field_FIELD_NOT_USED
}

func (x *Value) GetStringVal() string {
	if x != nil && x.StringVal != nil {
		return *x.StringVal
	}
	return ""
}

func (x *Value) GetInt64Val() int64 {
	if x != nil && x.Int64Val != nil {
		return *x.Int64Val
	}
	return 0
}

func (x *Value) GetFloat64Val() float64 {
	if x != nil && x.Float64Val != nil {
		return *x.Float64Val
	}
	return 0
}

func (x *Value) GetBoolVal() bool {
	if x != nil && x.BoolVal != nil {
		return *x.BoolVal
	}
	return false
}

type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeriodType             `protobuf:"varint,1,opt,name=Type,proto3,enum=aed.PeriodType" json:"Type,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"` // The duration of the indicated period (e.g 1 minute, 3 minutes, etc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_aed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{3}
}

func (x *Period) GetType() PeriodType {
	if x != nil {
		return x.Type
	}
	return PeriodType_PERIOD_TYPE_DO_NOT_USE
}

func (x *Period) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_aed_proto protoreflect.FileDescriptor

const file_aed_proto_rawDesc = "" +
	"\n" +
	"\taed.proto\x12\x03aed\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"$\n" +
	"\x04AEDs\x12\x1c\n" +
	"\x04AEDs\x18\x01 \x03(\v2\b.aed.AEDR\x04AEDs\"\xf8\x02\n" +
	"\x03AED\x12&\n" +
	"\x0eOrganizationID\x18\x01 \x01(\tR\x0eOrganizationID\x12\x16\n" +
	"\x06Symbol\x18\x02 \x01(\tR\x06Symbol\x128\n" +
	"\tTimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12#\n" +
	"\x06Period\x18\x04 \x01(\v2\v.aed.PeriodR\x06Period\x12.\n" +
	"\bMetaData\x18\x05 \x01(\v2\x12.metadata.MetaDataR\bMetaData\x12\x1b\n" +
	"\x06UserID\x18\x06 \x01(\tH\x00R\x06UserID\x88\x01\x01\x12 \n" +
	"\x05Value\x18d \x03(\v2\n" +
	".aed.ValueR\x05Value\x12#\n" +
	"\x06Series\x18e \x01(\x0e2\v.aed.SeriesR\x06Series\x12(\n" +
	"\x06Source\x18f \x01(\x0e2\v.aed.SourceH\x01R\x06Source\x88\x01\x01B\t\n" +
	"\a_UserIDB\t\n" +
	"\a_Source\"\xd1\x03\n" +
	"\x05Value\x12*\n" +
	"\x05Field\x18\x01 \x01(\x0e2\n" +
	".aed.FieldB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05Field\x12!\n" +
	"\tStringVal\x18\x02 \x01(\tH\x00R\tStringVal\x88\x01\x01\x12(\n" +
	"\bInt64Val\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02(\x00H\x01R\bInt64Val\x88\x01\x01\x12,\n" +
	"\n" +
	"Float64Val\x18\x04 \x01(\x01B\a\xbaH\x04\x12\x02@\x01H\x02R\n" +
	"Float64Val\x88\x01\x01\x12\x1d\n" +
	"\aBoolVal\x18\x05 \x01(\bH\x03R\aBoolVal\x88\x01\x01:\xcb\x01\xbaH\xc7\x01\x1a\xc4\x01\n" +
	"\x12ohlc_float_gt_zero\x12UOPEN/HIGH/LOW/CLOSE/FIRST_PRICE/LAST_PRICE Float64Val must be greater than 0 when set\x1aW!(this.Field in [1, 2, 3, 4, 14, 15]) || !has(this.Float64Val) || this.Float64Val > 0.0B\f\n" +
	"\n" +
	"_StringValB\v\n" +
	"\t_Int64ValB\r\n" +
	"\v_Float64ValB\n" +
	"\n" +
	"\b_BoolVal\"^\n" +
	"\x06Period\x12/\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x0f.aed.PeriodTypeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04Type\x12#\n" +
	"\bDuration\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bDuration*g\n" +
	"\x06Source\x12\x13\n" +
	"\x0fSOURCE_NOT_USED\x10\x00\x12\x13\n" +
	"\x0fSOURCE_EXCHANGE\x10\x01\x12\x0e\n" +
	"\n" +
	"SOURCE_ATS\x10\x02\x12\x0e\n" +
	"\n" +
	"SOURCE_DEX\x10\x03\x12\x13\n" +
	"\x0fSOURCE_INTERNAL\x10\x04*{\n" +
	"\x06Series\x12\x13\n" +
	"\x0fSERIES_NOT_USED\x10\x00\x12\x13\n" +
	"\x0fINTERNAL_TRADES\x10\x01\x12\x16\n" +
	"\x12MARKET_DATA_STOCKS\x10\x02\x12\x14\n" +
	"\x10USER_PERFORMANCE\x10\x03\x12\v\n" +
	"\aBILLING\x10\x04\x12\f\n" +
	"\bREFERRAL\x10\x05*\xec\x01\n" +
	"\x05Field\x12\x12\n" +
	"\x0eFIELD_NOT_USED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\a\n" +
	"\x03LOW\x10\x03\x12\t\n" +
	"\x05CLOSE\x10\x04\x12\n" +
	"\n" +
	"\x06VOLUME\x10\x05\x12\x14\n" +
	"\x10NUMBER_OF_TRADES\x10\x06\x12\x13\n" +
	"\x0fINVERTED_VOLUME\x10\a\x12\x0e\n" +
	"\n" +
	"MARKET_CAP\x10\b\x12\a\n" +
	"\x03EPS\x10\t\x12\f\n" +
	"\bPE_RATIO\x10\n" +
	"\x12\t\n" +
	"\x05YIELD\x10\v\x12\r\n" +
	"\tOPEN_TIME\x10\f\x12\x0e\n" +
	"\n" +
	"CLOSE_TIME\x10\r\x12\x0f\n" +
	"\vFIRST_PRICE\x10\x0e\x12\x0e\n" +
	"\n" +
	"LAST_PRICE\x10\x0f*\xae\x01\n" +
	"\n" +
	"PeriodType\x12\x1a\n" +
	"\x16PERIOD_TYPE_DO_NOT_USE\x10\x00\x12\x16\n" +
	"\x12PERIOD_TYPE_MINUTE\x10\x01\x12\x14\n" +
	"\x10PERIOD_TYPE_HOUR\x10\x02\x12\x13\n" +
	"\x0fPERIOD_TYPE_DAY\x10\x03\x12\x14\n" +
	"\x10PERIOD_TYPE_WEEK\x10\x04\x12\x15\n" +
	"\x11PERIOD_TYPE_MONTH\x10\x05\x12\x14\n" +
	"\x10PERIOD_TYPE_YEAR\x10\x06B+Z)github.com/sologenic/com-fs-aed-model;aedb\x06proto3"

var (
	file_aed_proto_rawDescOnce sync.Once
	file_aed_proto_rawDescData []byte
)

func file_aed_proto_rawDescGZIP() []byte {
	file_aed_proto_rawDescOnce.Do(func() {
		file_aed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aed_proto_rawDesc), len(file_aed_proto_rawDesc)))
	})
	return file_aed_proto_rawDescData
}

var file_aed_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_aed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aed_proto_goTypes = []any{
	(Source)(0),                   // 0: aed.Source
	(Series)(0),                   // 1: aed.Series
	(Field)(0),                    // 2: aed.Field
	(PeriodType)(0),               // 3: aed.PeriodType
	(*AEDs)(nil),                  // 4: aed.AEDs
	(*AED)(nil),                   // 5: aed.AED
	(*Value)(nil),                 // 6: aed.Value
	(*Period)(nil),                // 7: aed.Period
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*metadata.MetaData)(nil),     // 9: metadata.MetaData
}
var file_aed_proto_depIdxs = []int32{
	5, // 0: aed.AEDs.AEDs:type_name -> aed.AED
	8, // 1: aed.AED.Timestamp:type_name -> google.protobuf.Timestamp
	7, // 2: aed.AED.Period:type_name -> aed.Period
	9, // 3: aed.AED.MetaData:type_name -> metadata.MetaData
	6, // 4: aed.AED.Value:type_name -> aed.Value
	1, // 5: aed.AED.Series:type_name -> aed.Series
	0, // 6: aed.AED.Source:type_name -> aed.Source
	2, // 7: aed.Value.Field:type_name -> aed.Field
	3, // 8: aed.Period.Type:type_name -> aed.PeriodType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_aed_proto_init() }
func file_aed_proto_init() {
	if File_aed_proto != nil {
		return
	}
	file_aed_proto_msgTypes[1].OneofWrappers = []any{}
	file_aed_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aed_proto_rawDesc), len(file_aed_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aed_proto_goTypes,
		DependencyIndexes: file_aed_proto_depIdxs,
		EnumInfos:         file_aed_proto_enumTypes,
		MessageInfos:      file_aed_proto_msgTypes,
	}.Build()
	File_aed_proto = out.File
	file_aed_proto_goTypes = nil
	file_aed_proto_depIdxs = nil
}
