// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.1
// source: aed.proto

package aed

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Series int32

const (
	Series_SERIES_NOT_USED    Series = 0
	Series_INTERNAL_TRADES    Series = 1 // Source: dex trades, Usage: general trade graphs, supports TradeView-like graphing tools (ohlc)
	Series_MARKET_DATA_STOCKS Series = 2 // Source: external market data provider for the general stock market (can be more than 1 provider, but only a single provider per stock)
)

// Enum value maps for Series.
var (
	Series_name = map[int32]string{
		0: "SERIES_NOT_USED",
		1: "INTERNAL_TRADES",
		2: "MARKET_DATA_STOCKS",
	}
	Series_value = map[string]int32{
		"SERIES_NOT_USED":    0,
		"INTERNAL_TRADES":    1,
		"MARKET_DATA_STOCKS": 2,
	}
)

func (x Series) Enum() *Series {
	p := new(Series)
	*p = x
	return p
}

func (x Series) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Series) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[0].Descriptor()
}

func (Series) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[0]
}

func (x Series) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Series.Descriptor instead.
func (Series) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{0}
}

type Field int32

const (
	Field_FIELD_NOT_USED   Field = 0
	Field_OPEN             Field = 1
	Field_HIGH             Field = 2
	Field_LOW              Field = 3
	Field_CLOSE            Field = 4
	Field_VOLUME           Field = 5
	Field_NUMBER_OF_TRADES Field = 6
	Field_INVERTED_VOLUME  Field = 7
	Field_MARKET_CAP       Field = 8
	Field_EPS              Field = 9
	Field_PE_RATIO         Field = 10
	Field_YIELD            Field = 11
	Field_OPEN_TIME        Field = 12
	Field_CLOSE_TIME       Field = 13
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0:  "FIELD_NOT_USED",
		1:  "OPEN",
		2:  "HIGH",
		3:  "LOW",
		4:  "CLOSE",
		5:  "VOLUME",
		6:  "NUMBER_OF_TRADES",
		7:  "INVERTED_VOLUME",
		8:  "MARKET_CAP",
		9:  "EPS",
		10: "PE_RATIO",
		11: "YIELD",
		12: "OPEN_TIME",
		13: "CLOSE_TIME",
	}
	Field_value = map[string]int32{
		"FIELD_NOT_USED":   0,
		"OPEN":             1,
		"HIGH":             2,
		"LOW":              3,
		"CLOSE":            4,
		"VOLUME":           5,
		"NUMBER_OF_TRADES": 6,
		"INVERTED_VOLUME":  7,
		"MARKET_CAP":       8,
		"EPS":              9,
		"PE_RATIO":         10,
		"YIELD":            11,
		"OPEN_TIME":        12,
		"CLOSE_TIME":       13,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[1].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[1]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field.Descriptor instead.
func (Field) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{1}
}

type PeriodType int32

const (
	PeriodType_PERIOD_TYPE_DO_NOT_USE PeriodType = 0
	PeriodType_PERIOD_TYPE_MINUTE     PeriodType = 1
	PeriodType_PERIOD_TYPE_HOUR       PeriodType = 2
	PeriodType_PERIOD_TYPE_DAY        PeriodType = 3
	PeriodType_PERIOD_TYPE_WEEK       PeriodType = 4
)

// Enum value maps for PeriodType.
var (
	PeriodType_name = map[int32]string{
		0: "PERIOD_TYPE_DO_NOT_USE",
		1: "PERIOD_TYPE_MINUTE",
		2: "PERIOD_TYPE_HOUR",
		3: "PERIOD_TYPE_DAY",
		4: "PERIOD_TYPE_WEEK",
	}
	PeriodType_value = map[string]int32{
		"PERIOD_TYPE_DO_NOT_USE": 0,
		"PERIOD_TYPE_MINUTE":     1,
		"PERIOD_TYPE_HOUR":       2,
		"PERIOD_TYPE_DAY":        3,
		"PERIOD_TYPE_WEEK":       4,
	}
)

func (x PeriodType) Enum() *PeriodType {
	p := new(PeriodType)
	*p = x
	return p
}

func (x PeriodType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeriodType) Descriptor() protoreflect.EnumDescriptor {
	return file_aed_proto_enumTypes[2].Descriptor()
}

func (PeriodType) Type() protoreflect.EnumType {
	return &file_aed_proto_enumTypes[2]
}

func (x PeriodType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeriodType.Descriptor instead.
func (PeriodType) EnumDescriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{2}
}

type AEDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AEDs []*AED `protobuf:"bytes,1,rep,name=AEDs,proto3" json:"AEDs,omitempty"`
}

func (x *AEDs) Reset() {
	*x = AEDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AEDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AEDs) ProtoMessage() {}

func (x *AEDs) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AEDs.ProtoReflect.Descriptor instead.
func (*AEDs) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{0}
}

func (x *AEDs) GetAEDs() []*AED {
	if x != nil {
		return x.AEDs
	}
	return nil
}

type AED struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationID string                 `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	MetaData       *metadata.MetaData     `protobuf:"bytes,4,opt,name=MetaData,proto3" json:"MetaData,omitempty"`
	Value          []*Value               `protobuf:"bytes,100,rep,name=Value,proto3" json:"Value,omitempty"`
	Series         Series                 `protobuf:"varint,101,opt,name=Series,proto3,enum=aed.Series" json:"Series,omitempty"`
}

func (x *AED) Reset() {
	*x = AED{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AED) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AED) ProtoMessage() {}

func (x *AED) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AED.ProtoReflect.Descriptor instead.
func (*AED) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{1}
}

func (x *AED) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *AED) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AED) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AED) GetMetaData() *metadata.MetaData {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *AED) GetValue() []*Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AED) GetSeries() Series {
	if x != nil {
		return x.Series
	}
	return Series_SERIES_NOT_USED
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field Field `protobuf:"varint,1,opt,name=Field,proto3,enum=aed.Field" json:"Field,omitempty"`
	// Types that are assignable to Value:
	//
	//	*Value_ValueStr
	//	*Value_ValueInt64
	//	*Value_ValueFloat64
	//	*Value_ValuePeriod
	Value isValue_Value `protobuf_oneof:"Value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetField() Field {
	if x != nil {
		return x.Field
	}
	return Field_FIELD_NOT_USED
}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value) GetValueStr() string {
	if x, ok := x.GetValue().(*Value_ValueStr); ok {
		return x.ValueStr
	}
	return ""
}

func (x *Value) GetValueInt64() int64 {
	if x, ok := x.GetValue().(*Value_ValueInt64); ok {
		return x.ValueInt64
	}
	return 0
}

func (x *Value) GetValueFloat64() float64 {
	if x, ok := x.GetValue().(*Value_ValueFloat64); ok {
		return x.ValueFloat64
	}
	return 0
}

func (x *Value) GetValuePeriod() *Period {
	if x, ok := x.GetValue().(*Value_ValuePeriod); ok {
		return x.ValuePeriod
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_ValueStr struct {
	ValueStr string `protobuf:"bytes,2,opt,name=ValueStr,proto3,oneof"`
}

type Value_ValueInt64 struct {
	ValueInt64 int64 `protobuf:"varint,3,opt,name=ValueInt64,proto3,oneof"`
}

type Value_ValueFloat64 struct {
	ValueFloat64 float64 `protobuf:"fixed64,4,opt,name=ValueFloat64,proto3,oneof"`
}

type Value_ValuePeriod struct {
	ValuePeriod *Period `protobuf:"bytes,5,opt,name=ValuePeriod,proto3,oneof"`
}

func (*Value_ValueStr) isValue_Value() {}

func (*Value_ValueInt64) isValue_Value() {}

func (*Value_ValueFloat64) isValue_Value() {}

func (*Value_ValuePeriod) isValue_Value() {}

type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     PeriodType `protobuf:"varint,1,opt,name=Type,proto3,enum=aed.PeriodType" json:"Type,omitempty"`
	Duration int32      `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"` // The duration of the indicated period (e.g 1 minute, 3 minutes, etc)
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aed_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_aed_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_aed_proto_rawDescGZIP(), []int{3}
}

func (x *Period) GetType() PeriodType {
	if x != nil {
		return x.Type
	}
	return PeriodType_PERIOD_TYPE_DO_NOT_USE
}

func (x *Period) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_aed_proto protoreflect.FileDescriptor

var file_aed_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x65, 0x64,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x39, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d,
	0x2d, 0x66, 0x73, 0x2d, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x04,
	0x41, 0x45, 0x44, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x41, 0x45, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x65, 0x64, 0x2e, 0x41, 0x45, 0x44, 0x52, 0x04, 0x41, 0x45,
	0x44, 0x73, 0x22, 0xf6, 0x01, 0x0a, 0x03, 0x41, 0x45, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x64, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x65, 0x64, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x65, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x61, 0x65, 0x64, 0x2e, 0x53, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x06, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0xc9, 0x01, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x61, 0x65, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x53, 0x74, 0x72, 0x12, 0x20, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x24, 0x0a, 0x0c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x0c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x2f, 0x0a,
	0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x65, 0x64, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x48,
	0x00, 0x52, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x07,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x49, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x23, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x61, 0x65, 0x64, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2a, 0x4a, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x13, 0x0a, 0x0f,
	0x53, 0x45, 0x52, 0x49, 0x45, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x54, 0x52,
	0x41, 0x44, 0x45, 0x53, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54,
	0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x53, 0x10, 0x02, 0x2a, 0xcb,
	0x01, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x49, 0x45, 0x4c,
	0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x4f, 0x50, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f,
	0x53, 0x45, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x4f, 0x4c, 0x55, 0x4d, 0x45, 0x10, 0x05,
	0x12, 0x14, 0x0a, 0x10, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x4f, 0x46, 0x5f, 0x54, 0x52,
	0x41, 0x44, 0x45, 0x53, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x56, 0x45, 0x52, 0x54,
	0x45, 0x44, 0x5f, 0x56, 0x4f, 0x4c, 0x55, 0x4d, 0x45, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x4d,
	0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x43, 0x41, 0x50, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x45,
	0x50, 0x53, 0x10, 0x09, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x10, 0x0a, 0x12, 0x09, 0x0a, 0x05, 0x59, 0x49, 0x45, 0x4c, 0x44, 0x10, 0x0b, 0x12, 0x0d, 0x0a,
	0x09, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x0d, 0x2a, 0x81, 0x01, 0x0a,
	0x0a, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x50,
	0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x4f, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x45, 0x52, 0x49, 0x4f,
	0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48,
	0x4f, 0x55, 0x52, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x41, 0x59, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x45,
	0x52, 0x49, 0x4f, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x45, 0x45, 0x4b, 0x10, 0x04,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d,
	0x61, 0x65, 0x64, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x3b, 0x61, 0x65, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aed_proto_rawDescOnce sync.Once
	file_aed_proto_rawDescData = file_aed_proto_rawDesc
)

func file_aed_proto_rawDescGZIP() []byte {
	file_aed_proto_rawDescOnce.Do(func() {
		file_aed_proto_rawDescData = protoimpl.X.CompressGZIP(file_aed_proto_rawDescData)
	})
	return file_aed_proto_rawDescData
}

var file_aed_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_aed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aed_proto_goTypes = []interface{}{
	(Series)(0),                   // 0: aed.Series
	(Field)(0),                    // 1: aed.Field
	(PeriodType)(0),               // 2: aed.PeriodType
	(*AEDs)(nil),                  // 3: aed.AEDs
	(*AED)(nil),                   // 4: aed.AED
	(*Value)(nil),                 // 5: aed.Value
	(*Period)(nil),                // 6: aed.Period
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*metadata.MetaData)(nil),     // 8: metadata.MetaData
}
var file_aed_proto_depIdxs = []int32{
	4, // 0: aed.AEDs.AEDs:type_name -> aed.AED
	7, // 1: aed.AED.Timestamp:type_name -> google.protobuf.Timestamp
	8, // 2: aed.AED.MetaData:type_name -> metadata.MetaData
	5, // 3: aed.AED.Value:type_name -> aed.Value
	0, // 4: aed.AED.Series:type_name -> aed.Series
	1, // 5: aed.Value.Field:type_name -> aed.Field
	6, // 6: aed.Value.ValuePeriod:type_name -> aed.Period
	2, // 7: aed.Period.Type:type_name -> aed.PeriodType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_aed_proto_init() }
func file_aed_proto_init() {
	if File_aed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AEDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AED); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aed_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_aed_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Value_ValueStr)(nil),
		(*Value_ValueInt64)(nil),
		(*Value_ValueFloat64)(nil),
		(*Value_ValuePeriod)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aed_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aed_proto_goTypes,
		DependencyIndexes: file_aed_proto_depIdxs,
		EnumInfos:         file_aed_proto_enumTypes,
		MessageInfos:      file_aed_proto_msgTypes,
	}.Build()
	File_aed_proto = out.File
	file_aed_proto_rawDesc = nil
	file_aed_proto_goTypes = nil
	file_aed_proto_depIdxs = nil
}
