// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.1
// source: assettimeseries-grpc.proto

package assettimeseries

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AssetTimeSeriesService_Upsert_FullMethodName      = "/assettimeseries.v1.AssetTimeSeriesService/Upsert"
	AssetTimeSeriesService_BatchUpsert_FullMethodName = "/assettimeseries.v1.AssetTimeSeriesService/BatchUpsert"
	AssetTimeSeriesService_GetBySymbol_FullMethodName = "/assettimeseries.v1.AssetTimeSeriesService/GetBySymbol"
)

// AssetTimeSeriesServiceClient is the client API for AssetTimeSeriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetTimeSeriesServiceClient interface {
	// Store a single AssetTimeSeries
	Upsert(ctx context.Context, in *AssetTimeSeries, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Store multiple AssetTimeSeries
	BatchUpsert(ctx context.Context, in *AssetTimeSeries, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get a list of AssetTimeSeries by from/to, symbol, period and network
	GetBySymbol(ctx context.Context, in *GetBySymbolOptions, opts ...grpc.CallOption) (*AssetTimeSeries, error)
}

type assetTimeSeriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetTimeSeriesServiceClient(cc grpc.ClientConnInterface) AssetTimeSeriesServiceClient {
	return &assetTimeSeriesServiceClient{cc}
}

func (c *assetTimeSeriesServiceClient) Upsert(ctx context.Context, in *AssetTimeSeries, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetTimeSeriesService_Upsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetTimeSeriesServiceClient) BatchUpsert(ctx context.Context, in *AssetTimeSeries, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetTimeSeriesService_BatchUpsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetTimeSeriesServiceClient) GetBySymbol(ctx context.Context, in *GetBySymbolOptions, opts ...grpc.CallOption) (*AssetTimeSeries, error) {
	out := new(AssetTimeSeries)
	err := c.cc.Invoke(ctx, AssetTimeSeriesService_GetBySymbol_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetTimeSeriesServiceServer is the server API for AssetTimeSeriesService service.
// All implementations should embed UnimplementedAssetTimeSeriesServiceServer
// for forward compatibility
type AssetTimeSeriesServiceServer interface {
	// Store a single AssetTimeSeries
	Upsert(context.Context, *AssetTimeSeries) (*emptypb.Empty, error)
	// Store multiple AssetTimeSeries
	BatchUpsert(context.Context, *AssetTimeSeries) (*emptypb.Empty, error)
	// Get a list of AssetTimeSeries by from/to, symbol, period and network
	GetBySymbol(context.Context, *GetBySymbolOptions) (*AssetTimeSeries, error)
}

// UnimplementedAssetTimeSeriesServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAssetTimeSeriesServiceServer struct {
}

func (UnimplementedAssetTimeSeriesServiceServer) Upsert(context.Context, *AssetTimeSeries) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedAssetTimeSeriesServiceServer) BatchUpsert(context.Context, *AssetTimeSeries) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpsert not implemented")
}
func (UnimplementedAssetTimeSeriesServiceServer) GetBySymbol(context.Context, *GetBySymbolOptions) (*AssetTimeSeries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBySymbol not implemented")
}

// UnsafeAssetTimeSeriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetTimeSeriesServiceServer will
// result in compilation errors.
type UnsafeAssetTimeSeriesServiceServer interface {
	mustEmbedUnimplementedAssetTimeSeriesServiceServer()
}

func RegisterAssetTimeSeriesServiceServer(s grpc.ServiceRegistrar, srv AssetTimeSeriesServiceServer) {
	s.RegisterService(&AssetTimeSeriesService_ServiceDesc, srv)
}

func _AssetTimeSeriesService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetTimeSeries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTimeSeriesServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTimeSeriesService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTimeSeriesServiceServer).Upsert(ctx, req.(*AssetTimeSeries))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetTimeSeriesService_BatchUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetTimeSeries)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTimeSeriesServiceServer).BatchUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTimeSeriesService_BatchUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTimeSeriesServiceServer).BatchUpsert(ctx, req.(*AssetTimeSeries))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetTimeSeriesService_GetBySymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBySymbolOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTimeSeriesServiceServer).GetBySymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTimeSeriesService_GetBySymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTimeSeriesServiceServer).GetBySymbol(ctx, req.(*GetBySymbolOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetTimeSeriesService_ServiceDesc is the grpc.ServiceDesc for AssetTimeSeriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetTimeSeriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assettimeseries.v1.AssetTimeSeriesService",
	HandlerType: (*AssetTimeSeriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _AssetTimeSeriesService_Upsert_Handler,
		},
		{
			MethodName: "BatchUpsert",
			Handler:    _AssetTimeSeriesService_BatchUpsert_Handler,
		},
		{
			MethodName: "GetBySymbol",
			Handler:    _AssetTimeSeriesService_GetBySymbol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assettimeseries-grpc.proto",
}
