// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.1
// source: ats-grpc.proto

package ats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ATSService_Upsert_FullMethodName      = "/ats.v1.ATSService/Upsert"
	ATSService_BatchUpsert_FullMethodName = "/ats.v1.ATSService/BatchUpsert"
	ATSService_GetBySymbol_FullMethodName = "/ats.v1.ATSService/GetBySymbol"
)

// ATSServiceClient is the client API for ATSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ATSServiceClient interface {
	// Store a single ATS
	Upsert(ctx context.Context, in *ATS, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Store multiple ATS
	BatchUpsert(ctx context.Context, in *ATSList, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get a list of ATS by from/to, symbol, period and network
	GetBySymbol(ctx context.Context, in *GetBySymbolOptions, opts ...grpc.CallOption) (*ATSList, error)
}

type aTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewATSServiceClient(cc grpc.ClientConnInterface) ATSServiceClient {
	return &aTSServiceClient{cc}
}

func (c *aTSServiceClient) Upsert(ctx context.Context, in *ATS, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ATSService_Upsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTSServiceClient) BatchUpsert(ctx context.Context, in *ATSList, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ATSService_BatchUpsert_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aTSServiceClient) GetBySymbol(ctx context.Context, in *GetBySymbolOptions, opts ...grpc.CallOption) (*ATSList, error) {
	out := new(ATSList)
	err := c.cc.Invoke(ctx, ATSService_GetBySymbol_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ATSServiceServer is the server API for ATSService service.
// All implementations should embed UnimplementedATSServiceServer
// for forward compatibility
type ATSServiceServer interface {
	// Store a single ATS
	Upsert(context.Context, *ATS) (*emptypb.Empty, error)
	// Store multiple ATS
	BatchUpsert(context.Context, *ATSList) (*emptypb.Empty, error)
	// Get a list of ATS by from/to, symbol, period and network
	GetBySymbol(context.Context, *GetBySymbolOptions) (*ATSList, error)
}

// UnimplementedATSServiceServer should be embedded to have forward compatible implementations.
type UnimplementedATSServiceServer struct {
}

func (UnimplementedATSServiceServer) Upsert(context.Context, *ATS) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedATSServiceServer) BatchUpsert(context.Context, *ATSList) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpsert not implemented")
}
func (UnimplementedATSServiceServer) GetBySymbol(context.Context, *GetBySymbolOptions) (*ATSList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBySymbol not implemented")
}

// UnsafeATSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ATSServiceServer will
// result in compilation errors.
type UnsafeATSServiceServer interface {
	mustEmbedUnimplementedATSServiceServer()
}

func RegisterATSServiceServer(s grpc.ServiceRegistrar, srv ATSServiceServer) {
	s.RegisterService(&ATSService_ServiceDesc, srv)
}

func _ATSService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ATS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATSServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATSService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATSServiceServer).Upsert(ctx, req.(*ATS))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATSService_BatchUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ATSList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATSServiceServer).BatchUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATSService_BatchUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATSServiceServer).BatchUpsert(ctx, req.(*ATSList))
	}
	return interceptor(ctx, in, info, handler)
}

func _ATSService_GetBySymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBySymbolOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ATSServiceServer).GetBySymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ATSService_GetBySymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ATSServiceServer).GetBySymbol(ctx, req.(*GetBySymbolOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// ATSService_ServiceDesc is the grpc.ServiceDesc for ATSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ATSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ats.v1.ATSService",
	HandlerType: (*ATSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _ATSService_Upsert_Handler,
		},
		{
			MethodName: "BatchUpsert",
			Handler:    _ATSService_BatchUpsert_Handler,
		},
		{
			MethodName: "GetBySymbol",
			Handler:    _ATSService_GetBySymbol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ats-grpc.proto",
}
