// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.1
// source: ats.proto

package ats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ATSs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ATSs []*ATS `protobuf:"bytes,1,rep,name=ATSs,proto3" json:"ATSs,omitempty"`
}

func (x *ATSs) Reset() {
	*x = ATSs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ATSs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATSs) ProtoMessage() {}

func (x *ATSs) ProtoReflect() protoreflect.Message {
	mi := &file_ats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATSs.ProtoReflect.Descriptor instead.
func (*ATSs) Descriptor() ([]byte, []int) {
	return file_ats_proto_rawDescGZIP(), []int{0}
}

func (x *ATSs) GetATSs() []*ATS {
	if x != nil {
		return x.ATSs
	}
	return nil
}

type ATS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network             string  `protobuf:"bytes,1,opt,name=Network,proto3" json:"Network,omitempty"`
	Symbol              string  `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	TimeStamp           int64   `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Open                float64 `protobuf:"fixed64,4,opt,name=Open,proto3" json:"Open,omitempty"`
	High                float64 `protobuf:"fixed64,5,opt,name=High,proto3" json:"High,omitempty"`
	Low                 float64 `protobuf:"fixed64,6,opt,name=Low,proto3" json:"Low,omitempty"`
	Close               float64 `protobuf:"fixed64,7,opt,name=Close,proto3" json:"Close,omitempty"`
	Volume              float64 `protobuf:"fixed64,8,opt,name=Volume,proto3" json:"Volume,omitempty"`
	NumberOfTrades      int64   `protobuf:"varint,9,opt,name=NumberOfTrades,proto3" json:"NumberOfTrades,omitempty"`
	Period              string  `protobuf:"bytes,10,opt,name=Period,proto3" json:"Period,omitempty"`
	InvertedVolume      float64 `protobuf:"fixed64,11,opt,name=InvertedVolume,proto3" json:"InvertedVolume,omitempty"`
	USD                 float64 `protobuf:"fixed64,12,opt,name=USD,proto3" json:"USD,omitempty"`
	PoolCommission      float64 `protobuf:"fixed64,13,opt,name=PoolCommission,proto3" json:"PoolCommission,omitempty"`           // Sum of the trade fees in the alpabetically defined base currency
	BalanceBaseCurrency float64 `protobuf:"fixed64,14,opt,name=BalanceBaseCurrency,proto3" json:"BalanceBaseCurrency,omitempty"` // Closing balance in the base currency
}

func (x *ATS) Reset() {
	*x = ATS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ATS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ATS) ProtoMessage() {}

func (x *ATS) ProtoReflect() protoreflect.Message {
	mi := &file_ats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ATS.ProtoReflect.Descriptor instead.
func (*ATS) Descriptor() ([]byte, []int) {
	return file_ats_proto_rawDescGZIP(), []int{1}
}

func (x *ATS) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ATS) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ATS) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ATS) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *ATS) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *ATS) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ATS) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *ATS) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ATS) GetNumberOfTrades() int64 {
	if x != nil {
		return x.NumberOfTrades
	}
	return 0
}

func (x *ATS) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *ATS) GetInvertedVolume() float64 {
	if x != nil {
		return x.InvertedVolume
	}
	return 0
}

func (x *ATS) GetUSD() float64 {
	if x != nil {
		return x.USD
	}
	return 0
}

func (x *ATS) GetPoolCommission() float64 {
	if x != nil {
		return x.PoolCommission
	}
	return 0
}

func (x *ATS) GetBalanceBaseCurrency() float64 {
	if x != nil {
		return x.BalanceBaseCurrency
	}
	return 0
}

var File_ats_proto protoreflect.FileDescriptor

var file_ats_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x04, 0x41, 0x54, 0x53, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x41,
	0x54, 0x53, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x54, 0x53, 0x52, 0x04, 0x41, 0x54, 0x53, 0x73, 0x22, 0x91, 0x03, 0x0a,
	0x03, 0x41, 0x54, 0x53, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x67, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x48, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03,
	0x4c, 0x6f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x6f, 0x77, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x26, 0x0a, 0x0e,
	0x49, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x49, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x53, 0x44, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x55, 0x53, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x6f, 0x6f, 0x6c, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e,
	0x50, 0x6f, 0x6f, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30,
	0x0a, 0x13, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x65, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x42, 0x61, 0x73, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d,
	0x61, 0x74, 0x73, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x3b, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ats_proto_rawDescOnce sync.Once
	file_ats_proto_rawDescData = file_ats_proto_rawDesc
)

func file_ats_proto_rawDescGZIP() []byte {
	file_ats_proto_rawDescOnce.Do(func() {
		file_ats_proto_rawDescData = protoimpl.X.CompressGZIP(file_ats_proto_rawDescData)
	})
	return file_ats_proto_rawDescData
}

var file_ats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ats_proto_goTypes = []interface{}{
	(*ATSs)(nil), // 0: ats.v1.ATSs
	(*ATS)(nil),  // 1: ats.v1.ATS
}
var file_ats_proto_depIdxs = []int32{
	1, // 0: ats.v1.ATSs.ATSs:type_name -> ats.v1.ATS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ats_proto_init() }
func file_ats_proto_init() {
	if File_ats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ATSs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ATS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ats_proto_goTypes,
		DependencyIndexes: file_ats_proto_depIdxs,
		MessageInfos:      file_ats_proto_msgTypes,
	}.Build()
	File_ats_proto = out.File
	file_ats_proto_rawDesc = nil
	file_ats_proto_goTypes = nil
	file_ats_proto_depIdxs = nil
}
